import React,{useCallback,useMemo,useState}from"react";
import{ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View}from"react-native";
import Ionicons from"@expo/vector-icons/Ionicons";
import{useFocusEffect}from"@react-navigation/native";
import{api}from"../../api/client";
import{colors}from"../../theme";

const dayKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${x.getMonth()}-${x.getDate()}`};
const sameDay=(a,b)=>dayKey(a)===dayKey(b);
const time=d=>new Date(d).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});
const longDate=d=>new Date(d).toLocaleDateString([],{weekday:"long",day:"numeric",month:"long"});
export default function ScheduleScreen(){
 const[items,setItems]=useState([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[selected,setSelected]=useState(new Date());
 const load=useCallback(async()=>{try{const r=await api.get("/sessions/me/upcoming");setItems(r.data)}finally{setLoading(false);setRefreshing(false)}},[]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 const days=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()+i);return d}),[]);
 const selectedItems=items.filter(x=>sameDay(x.start_at,selected));
 const next=items[0];
 return <View style={s.screen}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load()}} tintColor={colors.cyan}/>}>
  <Text style={s.eyebrow}>YOUR TIMETABLE</Text><Text style={s.title}>Schedule</Text><Text style={s.subtitle}>Classes created by your tutor appear here automatically.</Text>
  {next&&<View style={s.nextCard}><View style={s.nextTop}><View style={s.icon}><Ionicons name="calendar" size={23} color={colors.cyan}/></View><View style={s.flex}><Text style={s.small}>NEXT CLASS</Text><Text style={s.nextTitle}>{next.module_code} · {next.title}</Text></View></View><Text style={s.nextDate}>{longDate(next.start_at)}</Text><Text style={s.nextTime}>{time(next.start_at)} – {time(next.end_at)}</Text><View style={s.meta}><Ionicons name={next.mode==="ONLINE"?"videocam-outline":"location-outline"} size={16} color={colors.muted}/><Text style={s.metaText}>{next.mode==="ONLINE"?"Online":next.location||"In person"}</Text></View></View>}
  <Text style={s.section}>THIS WEEK</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.days}>{days.map(d=>{const chosen=sameDay(d,selected),has=items.some(x=>sameDay(x.start_at,d));return <Pressable key={dayKey(d)} onPress={()=>setSelected(d)} style={[s.day,chosen&&s.daySelected]}><Text style={[s.dayName,chosen&&s.selectedText]}>{d.toLocaleDateString([],{weekday:"short"}).toUpperCase()}</Text><Text style={[s.dayNumber,chosen&&s.selectedText]}>{d.getDate()}</Text>{has?<View style={[s.dot,chosen&&s.dotSelected]}/>:<View style={s.dotSpace}/>}</Pressable>})}</ScrollView>
  <View style={s.dateRow}><Text style={s.sectionDate}>{longDate(selected)}</Text><Text style={s.count}>{selectedItems.length} {selectedItems.length===1?"class":"classes"}</Text></View>
  {loading?<ActivityIndicator color={colors.cyan} style={{marginTop:30}}/>:selectedItems.length===0?<View style={s.empty}><Ionicons name="calendar-clear-outline" size={30} color={colors.cyan}/><Text style={s.emptyTitle}>No classes scheduled</Text><Text style={s.emptyText}>Enjoy the free time. New tutor-created sessions will show here.</Text></View>:selectedItems.map(x=><View key={x.id} style={s.session}><View style={s.timeCol}><Text style={s.start}>{time(x.start_at)}</Text><Text style={s.end}>{time(x.end_at)}</Text></View><View style={s.line}/><View style={s.flex}><View style={s.row}><Text style={s.module}>{x.module_code||"MODULE"}</Text><Text style={s.tier}>{(x.tier||"").replaceAll("_"," ")}</Text></View><Text style={s.sessionTitle}>{x.title}</Text>{x.notes?<Text style={s.notes}>{x.notes}</Text>:null}<View style={s.meta}><Ionicons name={x.mode==="ONLINE"?"videocam-outline":"location-outline"} size={16} color={colors.cyan}/><Text style={s.location}>{x.mode==="ONLINE"?"Online session":x.location||"In person"}</Text></View></View></View>)}
 </ScrollView></View>
}
const s=StyleSheet.create({
 screen:{flex:1,backgroundColor:colors.background},content:{padding:20,paddingBottom:100},eyebrow:{color:colors.cyan,fontSize:11,fontWeight:"900",letterSpacing:1.5,marginTop:5},title:{color:colors.white,fontSize:30,fontWeight:"900",marginTop:5},subtitle:{color:colors.muted,fontSize:13,lineHeight:19,marginTop:5},
 nextCard:{backgroundColor:colors.card,borderWidth:1,borderColor:"#21627A",borderRadius:22,padding:17,marginTop:22},nextTop:{flexDirection:"row",alignItems:"center",gap:11},icon:{width:44,height:44,borderRadius:14,backgroundColor:"#09243A",alignItems:"center",justifyContent:"center"},flex:{flex:1},small:{color:colors.cyan,fontSize:9,fontWeight:"900",letterSpacing:1.2},nextTitle:{color:colors.white,fontSize:17,fontWeight:"900",marginTop:3},nextDate:{color:"#CBD5E1",fontWeight:"800",marginTop:16},nextTime:{color:colors.white,fontSize:22,fontWeight:"900",marginTop:3},
 meta:{flexDirection:"row",alignItems:"center",gap:6,marginTop:9},metaText:{color:colors.muted,fontSize:12},section:{color:colors.muted,fontSize:11,fontWeight:"900",letterSpacing:1.5,marginTop:27,marginBottom:10},days:{gap:8,paddingRight:10},day:{width:55,alignItems:"center",paddingVertical:10,borderRadius:16,backgroundColor:"#0B1426",borderWidth:1,borderColor:"#17243B"},daySelected:{backgroundColor:colors.cyan,borderColor:colors.cyan},dayName:{color:colors.muted,fontSize:9,fontWeight:"900"},dayNumber:{color:colors.white,fontSize:18,fontWeight:"900",marginTop:5},selectedText:{color:"#04111D"},dot:{width:5,height:5,borderRadius:3,backgroundColor:colors.cyan,marginTop:6},dotSelected:{backgroundColor:"#04111D"},dotSpace:{height:11},
 dateRow:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:25,marginBottom:10,gap:10},sectionDate:{color:colors.white,fontWeight:"900",fontSize:16,flex:1},count:{color:colors.muted,fontSize:11},
 session:{flexDirection:"row",backgroundColor:colors.card,borderWidth:1,borderColor:"#1E293B",borderRadius:19,padding:15,marginBottom:11},timeCol:{width:57},start:{color:colors.white,fontWeight:"900",fontSize:13},end:{color:colors.muted,fontSize:11,marginTop:5},line:{width:3,borderRadius:2,backgroundColor:colors.cyan,marginRight:13},row:{flexDirection:"row",alignItems:"center",gap:7,flexWrap:"wrap"},module:{color:colors.cyan,fontSize:10,fontWeight:"900",letterSpacing:1},tier:{color:"#CBD5E1",fontSize:9,fontWeight:"800",backgroundColor:"#172033",paddingHorizontal:7,paddingVertical:3,borderRadius:10},sessionTitle:{color:colors.white,fontWeight:"900",fontSize:16,marginTop:7},notes:{color:colors.muted,fontSize:12,lineHeight:17,marginTop:5},location:{color:"#BAE6FD",fontSize:12,fontWeight:"700"},
 empty:{alignItems:"center",backgroundColor:colors.card,borderWidth:1,borderColor:"#1E293B",borderRadius:19,padding:26},emptyTitle:{color:colors.white,fontSize:16,fontWeight:"900",marginTop:10},emptyText:{color:colors.muted,fontSize:12,textAlign:"center",lineHeight:18,marginTop:5}
});