import React,{useEffect,useRef,useState}from"react";
import{Animated,SafeAreaView,ScrollView,StyleSheet,Text,TouchableOpacity,View,useWindowDimensions}from"react-native";

const words=["LEARN.","CODE.","SUCCEED."];
export default function WelcomeScreen({navigation}){
 const{width,height}=useWindowDimensions(),small=width<370;
 const scrollRef=useRef(null);const sections=useRef({});const[y,setY]=useState(0);
 const[type,setType]=useState("");const[word,setWord]=useState(0);const[deleting,setDeleting]=useState(false);
 const intro=useRef(new Animated.Value(0)).current;const lift=useRef(new Animated.Value(20)).current;const float=useRef(new Animated.Value(0)).current;
 useEffect(()=>{Animated.parallel([Animated.timing(intro,{toValue:1,duration:650,useNativeDriver:true}),Animated.spring(lift,{toValue:0,tension:45,friction:8,useNativeDriver:true})]).start();Animated.loop(Animated.sequence([Animated.timing(float,{toValue:1,duration:2200,useNativeDriver:true}),Animated.timing(float,{toValue:0,duration:2200,useNativeDriver:true})])).start()},[]);
 useEffect(()=>{const full=words[word];const done=type===full,empty=type==="";const delay=done&&!deleting?900:deleting?55:95;const t=setTimeout(()=>{if(done&&!deleting){setDeleting(true);return}if(empty&&deleting){setDeleting(false);setWord((word+1)%words.length);return}setType(deleting?full.slice(0,Math.max(0,type.length-1)):full.slice(0,type.length+1))},delay);return()=>clearTimeout(t)},[type,word,deleting]);
 const jump=k=>scrollRef.current?.scrollTo({y:Math.max(0,(sections.current[k]||0)-68),animated:true});const drift=float.interpolate({inputRange:[0,1],outputRange:[0,12]});
 return <SafeAreaView style={s.page}>
  <View style={s.nav}><TouchableOpacity onPress={()=>scrollRef.current?.scrollTo({y:0,animated:true})} style={s.brandRow}><View style={s.logo}><Text style={s.logoText}>{"</>"}</Text></View><View><Text style={s.brand}>Code Ready <Text style={s.brandCyan}>Tutors</Text></Text><Text style={s.brandSub}>LEARN • CODE • SUCCEED</Text></View></TouchableOpacity><TouchableOpacity style={s.menu} onPress={()=>setY(y?0:1)}><Text style={s.menuText}>☰</Text></TouchableOpacity></View>
  {!!y&&<View style={s.mobileNav}><TouchableOpacity onPress={()=>{jump("modules");setY(0)}}><Text style={s.mobileLink}>Modules</Text></TouchableOpacity><TouchableOpacity onPress={()=>{jump("why");setY(0)}}><Text style={s.mobileLink}>Why Us</Text></TouchableOpacity><TouchableOpacity onPress={()=>{jump("pricing");setY(0)}}><Text style={s.mobileLink}>Pricing</Text></TouchableOpacity><TouchableOpacity style={s.mobileLogin} onPress={()=>navigation.navigate("Login")}><Text style={s.mobileLoginText}>Login / Register</Text></TouchableOpacity></View>}
  <ScrollView ref={scrollRef} contentContainerStyle={[s.content,{paddingHorizontal:small?17:21}]} showsVerticalScrollIndicator={false}>
   <Animated.View style={[s.hero,{minHeight:Math.max(620,height-66),paddingTop:Math.max(48,height*.1),opacity:intro,transform:[{translateY:lift}]}]}>
    <Text style={s.typed}>{type}<Text style={s.cursor}>|</Text></Text>
    <Text style={[s.heroTitle,{fontSize:small?43:49}]}>Master Code.</Text><Text style={[s.heroAccent,{fontSize:small?43:49}]}>Build Futures.</Text><Text style={[s.heroTitle,{fontSize:small?43:49}]}>Be Ready.</Text>
    <Text style={s.heroCopy}>Expert one-on-one and group tutoring for first-year computer science students. Clear explanations, step-by-step problem solving, and focused exam preparation.</Text>
    <View style={s.actions}><TouchableOpacity style={s.primary} onPress={()=>navigation.navigate("Register")}><Text style={s.primaryText}>Book a session</Text><Text style={s.primaryArrow}>↗</Text></TouchableOpacity><TouchableOpacity style={s.ghost} onPress={()=>jump("modules")}><Text style={s.ghostText}>View modules</Text></TouchableOpacity></View>
    <View style={s.proof}><Text style={s.proofText}>◆ First-year focused</Text><Text style={s.proofText}>✦ Better understanding</Text><Text style={s.proofText}>↗ Better results</Text></View>
    <Animated.View style={[s.codeWindow,{transform:[{translateY:drift}]}]}><View style={s.windowTop}><View style={[s.dot,{backgroundColor:"#FB7185"}]}/><View style={[s.dot,{backgroundColor:"#FBBF24"}]}/><View style={[s.dot,{backgroundColor:"#34D399"}]}/></View><Text style={s.codePink}>def <Text style={s.codeWhite}>be_ready(student):</Text></Text><Text style={s.code}>  student.skills += "code"</Text><Text style={s.code}>  while not student.confident:</Text><Text style={s.codeCyan}>    student.practice()</Text><Text style={s.codePink}>  return <Text style={s.codeWhite}>"Start strong. Stay ahead."</Text></Text></Animated.View>
   </Animated.View>

   <View onLayout={e=>sections.current.modules=e.nativeEvent.layout.y} style={s.section}><Text style={s.eyebrow}>MODULES</Text><Text style={s.sectionTitle}>Learn what matters.</Text><Text style={s.sectionCopy}>Focused support for the modules you are actually taking.</Text><View style={s.module}><View><Text style={s.moduleCode}>CSI141</Text><Text style={s.moduleName}>Programming Principles</Text><Text style={s.moduleCopy}>Build logic, problem-solving and programming confidence from the ground up.</Text></View><Text style={s.moduleArrow}>↗</Text></View><View style={s.module}><View><Text style={s.moduleCode}>CSI161</Text><Text style={s.moduleName}>Introduction to Computing</Text><Text style={s.moduleCopy}>Make computing fundamentals easier to understand, remember and apply.</Text></View><Text style={s.moduleArrow}>↗</Text></View></View>

   <View onLayout={e=>sections.current.why=e.nativeEvent.layout.y} style={s.section}><Text style={s.eyebrow}>WHY US</Text><Text style={s.sectionTitle}>A better way to get unstuck.</Text><View style={s.whyBox}><View style={s.whyItem}><Text style={s.whyNo}>01</Text><View><Text style={s.whyTitle}>Understand</Text><Text style={s.whyCopy}>Simple explanations without unnecessary complexity.</Text></View></View><View style={s.whyItem}><Text style={s.whyNo}>02</Text><View><Text style={s.whyTitle}>Practice</Text><Text style={s.whyCopy}>Examples and assessment-style questions that build skill.</Text></View></View><View style={[s.whyItem,{borderBottomWidth:0}]}><Text style={s.whyNo}>03</Text><View><Text style={s.whyTitle}>Perform</Text><Text style={s.whyCopy}>Go into quizzes, tests and exams with confidence.</Text></View></View></View></View>

   <View onLayout={e=>sections.current.pricing=e.nativeEvent.layout.y} style={s.section}><Text style={s.eyebrow}>PRICING</Text><View style={s.priceBox}><View><Text style={s.price}>P150</Text><Text style={s.per}>PER MODULE</Text></View><View style={s.priceSide}><Text style={s.priceTitle}>Simple. Student-friendly.</Text><Text style={s.priceCopy}>CSI141 or CSI161. Focused tutoring without complicated plans.</Text></View></View></View>

   <View style={s.loginSection}><Text style={s.eyebrow}>READY?</Text><Text style={s.loginTitle}>Start strong. Stay ahead.</Text><Text style={s.loginCopy}>New here? Create your student account. Already part of Code Ready? Jump back in.</Text><TouchableOpacity style={s.fullPrimary} onPress={()=>navigation.navigate("Register")}><Text style={s.fullPrimaryText}>Create student account</Text><Text style={s.primaryArrow}>→</Text></TouchableOpacity><TouchableOpacity style={s.fullGhost} onPress={()=>navigation.navigate("Login")}><Text style={s.fullGhostText}>Sign in</Text></TouchableOpacity></View>
   <Text style={s.footer}>CODE READY TUTORS  •  LEARN. CODE. SUCCEED.</Text>
  </ScrollView>
 </SafeAreaView>
}
const s=StyleSheet.create({
 page:{flex:1,backgroundColor:"#05080D"},content:{width:"100%",maxWidth:600,alignSelf:"center",paddingBottom:40},
 nav:{height:66,paddingHorizontal:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between",backgroundColor:"#070B11",borderBottomWidth:1,borderBottomColor:"#17202B",zIndex:20},brandRow:{flexDirection:"row",alignItems:"center"},logo:{width:34,height:34,borderRadius:10,backgroundColor:"#0B2B32",alignItems:"center",justifyContent:"center",marginRight:9},logoText:{color:"#22D3EE",fontSize:12,fontWeight:"900"},brand:{color:"#F8FAFC",fontSize:13,fontWeight:"900"},brandCyan:{color:"#22D3EE"},brandSub:{color:"#52606D",fontSize:5.5,fontWeight:"900",letterSpacing:1.2,marginTop:2},menu:{width:38,height:38,alignItems:"center",justifyContent:"center"},menuText:{color:"#E2E8F0",fontSize:20},
 mobileNav:{position:"absolute",top:66,left:12,right:12,zIndex:30,backgroundColor:"#0B111A",borderWidth:1,borderColor:"#1D2A38",borderRadius:16,padding:9},mobileLink:{color:"#D9E2EC",fontSize:13,fontWeight:"700",padding:13},mobileLogin:{backgroundColor:"#22D3EE",borderRadius:11,padding:12,marginTop:3},mobileLoginText:{color:"#041116",fontSize:12,fontWeight:"900",textAlign:"center"},
 hero:{paddingBottom:52,justifyContent:"flex-start"},typed:{color:"#22D3EE",fontSize:11,fontWeight:"900",letterSpacing:2.3,minHeight:18,marginBottom:17},cursor:{color:"#F8FAFC"},heroTitle:{color:"#F8FAFC",fontWeight:"900",lineHeight:52,letterSpacing:-2},heroAccent:{color:"#67E8F9",fontWeight:"900",lineHeight:52,letterSpacing:-2},heroCopy:{color:"#8D99A8",fontSize:14,lineHeight:22,marginTop:21},actions:{flexDirection:"row",alignItems:"center",marginTop:25},primary:{height:46,backgroundColor:"#67E8F9",borderRadius:23,flexDirection:"row",alignItems:"center",paddingLeft:18,paddingRight:7},primaryText:{color:"#051116",fontSize:12,fontWeight:"900"},primaryArrow:{color:"#051116",fontSize:17,fontWeight:"900",marginLeft:13},ghost:{height:46,justifyContent:"center",paddingHorizontal:17},ghostText:{color:"#D3DEE8",fontSize:11,fontWeight:"800"},proof:{flexDirection:"row",flexWrap:"wrap",gap:13,marginTop:28},proofText:{color:"#7D8C9D",fontSize:9,fontWeight:"700"},
 codeWindow:{marginTop:38,backgroundColor:"#0C1420",borderWidth:1,borderColor:"#203143",borderRadius:18,padding:17},windowTop:{flexDirection:"row",gap:6,marginBottom:17},dot:{width:7,height:7,borderRadius:4},code:{fontFamily:"monospace",color:"#9BAABD",fontSize:10,lineHeight:19},codePink:{fontFamily:"monospace",color:"#F472B6",fontSize:10,lineHeight:19},codeWhite:{color:"#E5EDF5"},codeCyan:{fontFamily:"monospace",color:"#67E8F9",fontSize:10,lineHeight:19},
 section:{paddingVertical:43,borderTopWidth:1,borderTopColor:"#141C26"},eyebrow:{color:"#22D3EE",fontSize:8,fontWeight:"900",letterSpacing:2.2,marginBottom:9},sectionTitle:{color:"#F4F7FA",fontSize:29,lineHeight:35,fontWeight:"900",letterSpacing:-.8},sectionCopy:{color:"#697788",fontSize:12,lineHeight:19,marginTop:8,marginBottom:20},module:{minHeight:142,backgroundColor:"#0A111A",borderWidth:1,borderColor:"#172534",borderRadius:17,padding:18,marginTop:11,flexDirection:"row",justifyContent:"space-between"},moduleCode:{color:"#22D3EE",fontSize:22,fontWeight:"900"},moduleName:{color:"#E8EEF4",fontSize:14,fontWeight:"800",marginTop:3},moduleCopy:{color:"#6F7F90",fontSize:11,lineHeight:17,marginTop:9,maxWidth:290},moduleArrow:{color:"#22D3EE",fontSize:18},
 whyBox:{marginTop:21,borderRadius:17,borderWidth:1,borderColor:"#172534",backgroundColor:"#091019",paddingHorizontal:17},whyItem:{flexDirection:"row",paddingVertical:18,borderBottomWidth:1,borderBottomColor:"#17212D"},whyNo:{color:"#22D3EE",fontSize:9,fontWeight:"900",marginRight:18,marginTop:3},whyTitle:{color:"#E8EEF4",fontSize:14,fontWeight:"800"},whyCopy:{color:"#6D7C8C",fontSize:11,lineHeight:17,marginTop:4,maxWidth:280},
 priceBox:{backgroundColor:"#67E8F9",borderRadius:18,padding:20,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},price:{color:"#041014",fontSize:37,fontWeight:"900",letterSpacing:-1.5},per:{color:"#086071",fontSize:7,fontWeight:"900",letterSpacing:1.5},priceSide:{width:"50%"},priceTitle:{color:"#041014",fontSize:13,fontWeight:"900"},priceCopy:{color:"#0A6675",fontSize:10,lineHeight:15,marginTop:5},
 loginSection:{paddingTop:44,paddingBottom:30},loginTitle:{color:"#F8FAFC",fontSize:32,lineHeight:38,fontWeight:"900",letterSpacing:-1},loginCopy:{color:"#748394",fontSize:12,lineHeight:19,marginTop:10,marginBottom:22},fullPrimary:{height:48,borderRadius:14,backgroundColor:"#F3FCFD",paddingHorizontal:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},fullPrimaryText:{color:"#061017",fontSize:12,fontWeight:"900"},fullGhost:{height:46,borderRadius:14,borderWidth:1,borderColor:"#1B3440",alignItems:"center",justifyContent:"center",marginTop:9},fullGhostText:{color:"#A9C8D0",fontSize:12,fontWeight:"800"},footer:{color:"#394654",fontSize:7,fontWeight:"900",letterSpacing:1.3,textAlign:"center",marginTop:20}
});